platform :android do
  desc 'Build the Android application.'
  lane :build do |options|
    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/')
  end
end

