name: 'React Native Android Build APK'
# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  merge:
    branches: [master]

jobs:
  # First Job
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      # For testing
      - name: Run tests
        run: |
          npm test
  # Second Job
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.x"
      - name: Install Fastlane
        run:  gem install fastlane
      - name: Build Apk
        run: |
          fastlane android build

